### Project Group ###
projectGroup=com.loopers
### Spring dependency versions ###
springBootVersion=3.4.4
springDependencyManagementVersion=1.1.7
springCloudDependenciesVersion=2024.0.1
### Library versions ###
springDocOpenApiVersion=2.7.0
mockitoVersion=5.14.0
instancioJUnitVersion=5.0.2
archUnitVersion=1.4.1
slackAppenderVersion=1.6.1
